apiVersion: apps/v1
kind: Deployment
metadata:
  name: netflix-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: netflix-app
  template:
    metadata:
      labels:
        app: netflix-app
    spec:
      containers:
      - name: netflix-app
        image: gode23/netflix-app:latest
        ports:
        - containerPort: 80
        env:
        - name: TMDB_V3_API_KEY
          valueFrom:
            secretKeyRef:
              name: tmdb-v3-api-key
              key: TMDB_V3_API_KEY