name: CI pipeline

on:
  push:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Clonacion del codigo
        uses: actions/checkout@v4
      
      #Necesario para SonarCloud
      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Listar variables JAVA_HOME
        run: |
          printenv | grep "JAVA_HOME"
    
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: SonarQube Quality Gate check
        uses: sonarsource/sonarqube-quality-gate-action@v1.1.0
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://sonarcloud.io

      #SCA
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'

      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install

      - name: Dependency Check
        uses: dependency-check/Dependency-Check_Action@1.1.0
        env:
          JAVA_HOME: /opt/jdk
        with:
          project: '${{ github.event.repository.name }}'
          path: '.'
          format: 'HTML'
          args: >
            --failOnCVSS 4
      
      - name: Upload Test Result
        uses: actions/upload-artifact@master
        with:
          name: DependencyCheck Report
          path: ${{github.workspace}}/reports

      - name: Analizar reporte de Dependency-Check
        run: |
          # Extraer el nivel de CVSS del reporte
          CVSS_LEVEL=$(grep -oP 'pkg:npm/[^@]+@[^ ]+ ([A-Z]+)' ${{github.workspace}}/reports/dependency-check-report.html | awk '{print $2}')

          # Verificar si el nivel de CVSS es mayor o igual a 4
          if [[ "$CVSS_LEVEL" == "CRITICAL" || "$CVSS_LEVEL" == "HIGH" || "$CVSS_LEVEL" == "MEDIUM" ]]; then
            echo "Se encontraron vulnerabilidades con CVSS > MEDIUM. La construcción fallará."
            exit 1
          else
            echo "No se encontraron vulnerabilidades críticas."
            echo "Nivel de CVSS encontrado: $CVSS_LEVEL"
          fi

           echo "Nivel de CVSS encontrado: $CVSS_LEVEL"